version: '3'

services:
  database:
    image: mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - scalabilidade:/var/lib/mysql
    networks:
    - interna
  courses.a:
    image: courses
    environment:
    - DB_HOST=database
    depends_on:
    - database
    restart: on-failure
    networks:
    - interna
  courses.b:
    image: courses
    environment:
      - DB_HOST=database
    depends_on:
      - database
    restart: on-failure
    networks:
      - interna
  proxy:
    image: nginx:alpine
    ports:
    - "8080:443"
    volumes:
    - ./src/main/resources/nginx/:/etc/nginx/conf.d/
    - ./src/main/resources/ssl/:/etc/nginx/ssl/
    depends_on:
    - courses.a
    - courses.b
    restart: on-failure
    networks:
    - interna
    - externa

volumes:
  scalabilidade:
networks:
  interna:
  externa:
