version: '3'

services:
  database:
    image: mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - scalabilidade:/var/lib/mysql
    networks:
    - interna

  courses:
    image: courses
    environment:
    - DB_HOST=database
    depends_on:
    - database
    restart: on-failure
    networks:
    - interna
  proxy:
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
    - ./src/main/resources/nginx/:/etc/nginx/conf.d/
    depends_on:
    - courses
    restart: on-failure
    networks:
    - interna
    - externa



volumes:
  scalabilidade:
networks:
  interna:
  externa:
